[package]
name = "dgui"
version = "0.1.0"
edition = "2024"
license = "MIT"
description = "A lightweight, reactive retained-mode GUI framework."
keywords = ["gui", "dgui"]
categories = ["gui"]
repository = "https://github.com/sumeeth05/dgui"
homepage = "https://github.com/sumeeth05/dgui"

[dependencies]
taffy = "0.13"
lyon = "1"
cosmic-text = "0.19"
etagere = "0.3"
keyframe = "1"
thiserror = "2"
svg = "0.18"
bytemuck = "1"
